build_windows_task:
  windows_container:
    dockerfile: ci/windows/Dockerfile
    os_version: 2019
  env:
    matrix:
      - ALLEGRO_RELEASE: v4.4.2-ags-14
        BUILD_CONFIG: Release
      - ALLEGRO_RELEASE: v4.4.2-ags-14
        BUILD_CONFIG: Debug
    AGS_DIRECTX_LIB: C:\Lib\DirectX
    AGS_LIBOGG_LIB: C:\Lib\Xiph
    AGS_LIBTHEORA_LIB: C:\Lib\Xiph
    AGS_LIBVORBIS_LIB: C:\Lib\Xiph
  build_script: >
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 &&
    set "AGS_ALLEGRO_INCLUDE=C:\Source\Allegro\%ALLEGRO_RELEASE%\include;C:\Source\Allegro\%ALLEGRO_RELEASE%\build\VS2015\include" &&
    set "AGS_ALLEGRO_LIB=C:\Lib\Allegro\%ALLEGRO_RELEASE%" &&
    cd Solutions &&
    msbuild Engine.sln /p:PlatformToolset=v140 /p:Configuration=%BUILD_CONFIG% /p:Platform=Win32 /maxcpucount /nologo

build_linux_task:
  container:
    dockerfile: ci/linux/Dockerfile
    docker_arguments:
      matrix:
        - FROM_DEBIAN: debian:jessie
        - FROM_DEBIAN: i386/debian:jessie
  env:
    matrix:
      - BUILD_SYSTEM: cmake
        BUILD_TYPE: release
      - BUILD_SYSTEM: cmake
        BUILD_TYPE: debug
      - BUILD_SYSTEM: debian
      - BUILD_SYSTEM: make
  build_script: |
    case $BUILD_SYSTEM in
      cmake)
        filename=ags_$BUILD_TYPE_$(dpkg --print-architecture)
        mkdir build_$filename && cd build_$filename
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make
        ;;
      debian)
        fakeroot debian/rules binary
        ;;
      make)
        make --directory=Engine
        ;;
      *)
        echo "Invalid build system"
        exit 1
        ;;
    esac

build_macos_task:
  osx_instance:
    matrix:
      - image: mojave-xcode-10.2
      - image: high-sierra-xcode-9.4.1
  env:
    matrix:
      - BUILD_TYPE: debug
      - BUILD_TYPE: release
    CMAKE_VERSION: 3.14.5
  install_cmake_script: |
    url="https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-Darwin-x86_64.tar.gz"
    echo "Downloading CMake from $url"
    curl -fLSs "$url" | bsdtar -f - -xvzC /Applications --strip-components 1
  build_script: |
    filename=ags_$BUILD_TYPE
    mkdir build_$filename && cd build_$filename
    /Applications/CMake.app/Contents/bin/cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make

build_editor_task:
  windows_container:
    dockerfile: ci/windows/Dockerfile
    os_version: 2019
  env:
    matrix:
      - BUILD_CONFIG: Release
      - BUILD_CONFIG: Debug
    ALLEGRO_RELEASE: v4.4.2-ags-14
    AGS_DIRECTX_LIB: C:\Lib\DirectX
  nuget_packages_cache:
    folder: Solutions\packages
    fingerprint_script: type Editor\AGS.Editor\packages.config
    populate_script: nuget restore Solutions\AGS.Editor.Full.sln
  build_script: >
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 &&
    set "AGS_ALLEGRO_INCLUDE=C:\Source\Allegro\%ALLEGRO_RELEASE%\include;C:\Source\Allegro\%ALLEGRO_RELEASE%\build\VS2015\include" &&
    set "AGS_ALLEGRO_LIB=C:\Lib\Allegro\%ALLEGRO_RELEASE%" &&
    set "LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86;C:\Program Files (x86)\Windows Kits\8.0\Lib\Win8\um\x86;" &&
    set "UseEnv=true" &&
    copy C:\Lib\irrKlang\*.dll Editor\References\ &&
    cd Solutions &&
    msbuild AGS.Editor.Full.sln /p:PlatformToolset=v140 /p:Configuration=%BUILD_CONFIG% /p:Platform="Mixed Platforms" /maxcpucount /nologo
