build_linux_task:
  container:
    dockerfile: ci/linux/Dockerfile
    docker_arguments:
      matrix:
        - FROM_DEBIAN: debian:jessie
        - FROM_DEBIAN: i386/debian:jessie
  env:
    matrix:
      - BUILD_SYSTEM: cmake
        BUILD_TYPE: release
      - BUILD_SYSTEM: cmake
        BUILD_TYPE: debug
      - BUILD_SYSTEM: debian
      - BUILD_SYSTEM: make
  build_script: |
    case $BUILD_SYSTEM in
      cmake)
        filename=ags_$BUILD_TYPE_$(dpkg --print-architecture)
        mkdir build_$filename && cd build_$filename
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make
        ;;
      debian)
        fakeroot debian/rules binary
        ;;
      make)
        make --directory=Engine
        ;;
      *)
        echo "Invalid build system"
        exit 1
        ;;
    esac

build_macos_task:
  osx_instance:
    matrix:
      - image: mojave-xcode-10.2
      - image: high-sierra-xcode-9.4.1
  env:
    matrix:
      - BUILD_TYPE: debug
      - BUILD_TYPE: release
  install_cmake_script: |
    export HOMEBREW_NO_INSTALL_CLEANUP=1
    brew update
    brew ls --versions cmake && brew upgrade cmake || brew install cmake
  build_script: |
    filename=ags_$BUILD_TYPE
    mkdir build_$filename && cd build_$filename
    cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make
